In [12]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [25]:
#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
# Import .csv file and convert it to a DataFrame object
df = pd.read_csv("Wholesale customers data.csv")
print(df.head())

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185


In [27]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB
None


##### From the above o/p, we can see there are no null values.

In [28]:
#Dropping the 1st two columns(as they are discrete)and with those columns we can't find any kind of similarity/dissimilarity
df.drop(['Channel','Region'],axis=1,inplace=True)

In [29]:
#Inorder to standardise the data we are converting to array format because StandardScaler fn. which comes from sklearn library
#works well with the array format of data, so we are converting our dataframe to array format
array=df.values

In [30]:
array

array([[12669,  9656,  7561,   214,  2674,  1338],
       [ 7057,  9810,  9568,  1762,  3293,  1776],
       [ 6353,  8808,  7684,  2405,  3516,  7844],
       ...,
       [14531, 15488, 30243,   437, 14841,  1867],
       [10290,  1981,  2232,  1038,   168,  2125],
       [ 2787,  1698,  2510,    65,   477,    52]], dtype=int64)

In [31]:
stdscaler=StandardScaler().fit(array)
X=stdscaler.transform(array) 
#Here,automatically the StandardScaler fn. will apply Z-Score standardisation on our data, and we will get the standardised 
#values which is stored in "X" variable.

In [32]:
X

array([[ 0.05293319,  0.52356777, -0.04111489, -0.58936716, -0.04356873,
        -0.06633906],
       [-0.39130197,  0.54445767,  0.17031835, -0.27013618,  0.08640684,
         0.08915105],
       [-0.44702926,  0.40853771, -0.0281571 , -0.13753572,  0.13323164,
         2.24329255],
       ...,
       [ 0.20032554,  1.31467078,  2.34838631, -0.54337975,  2.51121768,
         0.12145607],
       [-0.13538389, -0.51753572, -0.60251388, -0.41944059, -0.56977032,
         0.21304614],
       [-0.72930698, -0.5559243 , -0.57322717, -0.62009417, -0.50488752,
        -0.52286938]])

##### On the above standardised data we are going to apply the DBSCAN algorithm

In [35]:
dbscan=DBSCAN(eps=2,min_samples=7)
dbscan.fit(X) #applying dbscan on our standardised data which is stored in 'X'

DBSCAN(eps=2, min_samples=7)

##### In the above code, the condition for min_pts is that it should be greater than D+1 (here D denotes no. of dimensions(i.e columns)).Here the no. of columns that we are using are 6, so min_pts = 6+1 = 7-->Thus min_samples=7

In [36]:
#Finding out the noisy data points from the dataset
#Noisy samples is identified by the label -1 and any other positive integers denotes the clusters
dbscan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1, -1, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

##### The above values changes, as we change the eps and min_samples value.

In [37]:
#Converting the above array fomat back to the dataframe
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [38]:
cl

cluster
0          0
1          0
2          0
3          0
4          0
..       ...
435        0
436        0
437        0
438        0
439        0

[440 rows x 1 columns]

In [39]:
#Joining the cluster membership with the original data
pd.concat([df,cl],axis=1)

Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicassen  cluster
0    12669   9656     7561     214              2674        1338        0
1     7057   9810     9568    1762              3293        1776        0
2     6353   8808     7684    2405              3516        7844        0
3    13265   1196     4221    6404               507        1788        0
4    22615   5410     7198    3915              1777        5185        0
..     ...    ...      ...     ...               ...         ...      ...
435  29703  12051    16027   13135               182        2204        0
436  39228   1431      764    4510                93        2346        0
437  14531  15488    30243     437             14841        1867        0
438  10290   1981     2232    1038               168        2125        0
439   2787   1698     2510      65               477          52        0

[440 rows x 7 columns]